### ISSUE TITLE
Relationship to shared_memory?

### ISSUE THREAD

**Issue by asajeffrey** [standard-ai/caring#2]
There's another crate with similar goals to this one, which is https://github.com/elast0ny/shared_memory-rs/ which https://github.com/asajeffrey/shared-data/ builds on. I wonder if there's a connection, and whether `shared_memory`'s support for other architectures can be used?

**Comment by asajeffrey** [comment]
cc @elast0ny

**Comment by Ekleog** [comment]
As far as I understand `shared_memory-rs`, its `SharedMem` appears to be doing much more than our `Shared` does, with all the locking.

OTOH, its `SharedMemRaw` appears to be more unsafe than our `Shared`, due to its not requiring `ProcSync`.

Overall, I think the big difference between `shared_memory-rs` and `shmem` is that `shmem` attempts to be as thin a wrapper around mmap as possible (while being safe thanks to requiring `ProcSync` -- being a thin wrapper also means exposing functions like `from_raw_fd` etc.), while `shared_memory` provides both a completely-unsafe and a locked version of shared memory.

Oh, and the last difference is that our `Shared` stores directly an object type, while `SharedMem` appears to provide interface only to a batch of memory.

Now, I say that based only on a quick skim of `shared_memory-rs`, maybe I'm mistaken about it?

**Comment by asajeffrey** [comment]
That seems accurate. The `shared_memory` crate is about getting a `*mut u8` pointing into shared memory, safely accessing it is another matter.

**Comment by Ekleog** [comment]
(closing, as the question appears to have been answered)
